### ISSUE TITLE
Add a `-q`/`--quiet` config option

### ISSUE THREAD

**Issue by tarkatronic** [underdog-tech/vulnbot#48]
# 🚀 Feature Request

## Is your feature request related to a problem? Please describe.
Right now you basically always get full info-level output to the command line unless you know how to disable it with the `LOG_LEVEL` environment variable. This isn't a great user experience, especially as we're adding the console reporter.

## Describe the solution you'd like
The `-q`/`--quiet` option should basically turn off all the console logger. No log messages of any level should appear.

**Comment by krishnaduttPanchagnula** [comment]
Hi @tarkatronic , i have implemented the pr. I have checked for logging at cmd/root.go and set it to stop if our flag is false. But i am not sure if this would stop logging in all places. Do  you have any insights?
